name: Build Module

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.ps1'
      - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      projectUri:
        description: The URI of the project to build
        type: string
        required: false
        default: https://github.com/brianwest/github-tools
      releaseNotes:
        description: Release notes for the build
        type: string
        required: false
        default: No release notes provided
      moduleVersion:
        description: The version of the module to build
        type: string
        required: false
        default: 0.0.

env:
  PROJECT_URI: ${{ github.event.inputs.projectUri }}
  RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
  MODULE_VERSION: ${{ github.event.inputs.moduleVersion }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install InvokeBuild Module
      shell: pwsh
      run: Install-Module -Name InvokeBuild -Force

    - name: Build Module
      shell: pwsh
      run: Invoke-Build -File ./build.ps1 -Task Build
