name: Build Module

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.ps1'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install InvokeBuild Module
      shell: pwsh
      run: Install-Module -Name InvokeBuild -Force

    - name: Build Module
      shell: pwsh
      run: Invoke-Build -File ./build.ps1 -Task Build
