name: Build Module

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - build.ps1
      - .github/workflows/build.yml

  workflow_dispatch:
    inputs:
      projectUri:
        description: The URI of the project to build
        type: string
        required: false
        default: https://github.com/brianwest/github-tools
      releaseNotes:
        description: Release notes for the build
        type: string
        required: false
        default: No release notes provided
      moduleVersion:
        description: The version of the module to build
        type: string
        required: false
        default: 0.0.0

env:
  PROJECT_URI: https://github.com/brianwest/github-tools
  RELEASE_NOTES: No release notes provided
  MODULE_VERSION: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install InvokeBuild Module
      shell: pwsh
      run: Install-Module -Name InvokeBuild -Force

    - name: Set Environment Variables
      shell: pwsh
      run: |
        Import-Module ./src/GitHubTools.psm1

        Set-GhVariable -Name REPO_NAME -Value '${{ github.repository }}'.Split('/')[1]

        if ('${{ github.event.inputs.projectUri }}')
        {
          Set-GhVariable -Name PROJECT_URI -Value '${{ github.event.inputs.projectUri }}'
        }

        if ('${{ github.event.inputs.releaseNotes }}')
        {
          Set-GhVariable -Name RELEASE_NOTES -Value '${{ github.event.inputs.releaseNotes }}'
        }

        if ('${{ github.event.inputs.moduleVersion }}')
        {
          Set-GhVariable -Name MODULE_VERSION -Value '${{ github.event.inputs.moduleVersion }}'
        }

    - name: Build Module
      shell: pwsh
      run: Invoke-Build -File ./build.ps1 -Task Build

    - name: Upload Built Module
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME }}-module-${{ env.MODULE_VERSION }}
        path: ${{ github.workspace }}/output
