name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'GitHubTools.pms1'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: |
        $config = New-PesterConfiguration
        $config.Run.Path = 'tests'
        $config.CodeCoverage.Enabled = $true
        $config.CodeCoverage.Path = '.'
        $config.Output.Verbosity = 'Detailed'
        Invoke-Pester -Configuration $config

    - name: Upload Code Coverage
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/coverage.xml
