on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      REPO_NAME: ${{ steps.set.outputs.REPO_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: test default output
        id: set
        shell: pwsh
        run: |
          Import-Module ./src/GhCloudOps.psm1

          Set-GhVariable -Name REPO_NAME -Value '${{ github.repository }}'.Split('/')[-1] -IsOutput -IsSecret

      - name: test masked output
        shell: pwsh
        run: Write-Host "MY_RUNTIME_SECRET=${{ steps.set.outputs.REPO_NAME }}"
  output:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: test output
        shell: pwsh
        run: Write-Host "MY_RUNTIME_SECRET=${{ needs.test.outputs.REPO_NAME }}"
