on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test default output
        shell: pwsh
        run: |
          Test-Path ./src/GhCloudOps.psm1

          Import-Module ./src/GhCloudOps.psm1

          Set-GhVariable -Name REPO_NAME -Value '${{ github.repository }}'.Split('/')[-1] -IsSecret

          # $generatedSecret = [guid]::NewGuid().ToString()
          # Write-Host "::add-mask::$generatedSecret"
          # Add-Content -Path $env:GITHUB_ENV -Value "MY_RUNTIME_SECRET=$generatedSecret"

      - name: test masked output
        shell: pwsh
        run: Write-Host "MY_RUNTIME_SECRET=$env:REPO_NAME"
