on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: test default output
        shell: pwsh
        run: |
          Import-Module ./src/GhCloudOps.psm1

          Set-GhVariable -Name REPO_NAME -Value '${{ github.repository }}'.Split('/')[-1] -IsSecret -IsOutput

      - name: test masked output
        shell: pwsh
        run: Write-Host "MY_RUNTIME_SECRET=$env:REPO_NAME"
  output:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: test output
        shell: pwsh
        run: Write-Host "MY_RUNTIME_SECRET=${{ needs.test.outputs.REPO_NAME }}"
