name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'GitHubTools.pms1'
      - '.github/workflows/tests.yml'

env:
  CODE_COVERAGE_PERCENT_TARGET: 80

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      shell: pwsh
      working-directory: ${{ github.workspace }}/tests
      run: |
        ./RunTests.ps1 -Path . -CoveragePercentTarget $env:CODE_COVERAGE_PERCENT_TARGET

    - name: Upload Code Coverage
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/coverage.xml
