name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'GitHubTools.pms1'
      - '.github/workflows/tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        Get-ChildItem

    - name: Run Tests
      shell: pwsh
      run: |
        $config = New-PesterConfiguration
        $config.Run.Path = Join-Path '${{ github.workspace }}' -ChildPath 'tests'
        $config.CodeCoverage.Enabled = $true
        $config.Output.Verbosity = 'Detailed'
        Invoke-Pester -Configuration $config
