name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'tests/**'
      - 'src/**'
      - 'build.ps1'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install External Modules
      shell: pwsh
      run: Install-Module -Name InvokeBuild, Az.KeyVault -Force

    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@v1.1
      with:
        path: ${{ github.workspace }}/src
        settings: ${{ github.workspace }}/.vscode/PSScriptAnalyzerSettings.psd1

    - name: Run Tests
      shell: pwsh
      run: Invoke-Build -File ./build.ps1 -Task Test

    - name: Upload Code Coverage
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/tests/coverage.xml
